version: '3.3'

services:
  buster:
    image: noiselabs/buster
    build: docker/buster
    volumes:
      - ./build/buster:/var/tmp/buster:delegated
      - ./docker/buster/entrypoint.py:/usr/local/bin/entrypoint.py:delegated
  ghost:
    image: noiselabs/ghost
    build:
      context: .
      dockerfile: docker/ghost/Dockerfile
    volumes:
      - ./config/config.development.json:/var/lib/ghost/config.development.json:delegated
      - ./config/config.production.json:/var/lib/ghost/config.production.json:delegated
      - ./ghost:/var/lib/ghost/content:delegated
      - ./docker/bin:/opt/ghost-base:delegated
  live:
    image: nginx
    volumes:
      - ./build/buster:/usr/share/nginx/html:delegated
    ports:
       - "80:80"
  web:
   image: nginx
   depends_on:
     - ghost
   volumes:
     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf