version: '3.3'

services:
  db_prod:
    image: mysql:8
    env_file: config/production.env
    volumes:
      - ghost-db-prod-data:/var/lib/mysql:delegated
  ghost:
    env_file: config/production.env
    depends_on:
      - db_prod
    command: ["/opt/ghost-base/wait-for-it.sh", "--timeout=30", "db_prod:3306", "--strict", "--", "/opt/ghost-base/ghost-start.sh", "prod"]
  web:
    ports:
      - "2368:80"

volumes:
  ghost-db-prod-data: