version: '3.3'

services:
  ghost:
    image: noiselabs/ghost:latest
    build:
      context: .
      dockerfile: docker/ghost/Dockerfile
    ports:
      - "12368:2368"
    volumes:
      - ./config/config.development.json:/var/lib/ghost/config.development.json:delegated
      - ./config/config.production.json:/var/lib/ghost/config.production.json:delegated
      - ./ghost:/var/lib/ghost/content:delegated
      - ./docker/bin:/opt/ghost-base:delegated
    env_file: config/development.env
    depends_on:
      - db_dev
    command: ["/opt/ghost-base/wait-for-it.sh", "--timeout=30", "db_dev:3306", "--strict", "--", "/opt/ghost-base/ghost-start.sh", "dev"]
  db_dev:
    image: mysql:8
    env_file: config/development.env
    volumes:
      - ghost-db-dev-data:/var/lib/mysql:delegated

volumes:
  ghost-db-dev-data: